name: Mi Primera Automatizacion

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Instalar Librerias
      run: pip install pandas scikit-learn
    - name: Ejecutar mi codigo
      run: python preprocesamiento.py
